changing header title

diff --git a/.github/workflows/integration.yml b/.github/workflows/integration.yml
--- a/.github/workflows/integration.yml
+++ b/.github/workflows/integration.yml
@@ -60,11 +60,11 @@ jobs:
               echo "Failed to change directory as required by me"
               exit 1
             fi
-            echo "Reseting Local Changes"
-              if ! git reset --hard; then
-                  echo "Failed to reset local changes"
-                  exit 1;
-              fi
+            # echo "Reseting Local Changes"
+            #   if ! git reset --hard; then
+            #       echo "Failed to reset local changes"
+            #       exit 1;
+            #   fi
             echo "Pulling latest code from origin/main"
             if ! git pull origin main; then
               echo "Failed to pull latest code"
